FROM ubuntu:20.04

ENV TZ=Asia/Taipei

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y isc-dhcp-client netcat telnet tcpdump iproute2 iputils-ping iputils-tracepath traceroute curl iperf3 python3

RUN setcap -r /usr/bin/ping

COPY init /usr/bin/init

ENTRYPOINT ["/usr/bin/init"]

