FROM nsc-lab-host AS builder

RUN mkdir -p /home/builder

WORKDIR /home/builder

RUN apt-get update && \
    apt-get install -y build-essential pkg-config libnl-3-dev libnl-route-3-dev libpcap-dev

COPY dygre ./dygre

WORKDIR /home/builder/dygre

RUN make all

# ---

FROM nsc-lab-host

RUN sed -i -E 's|#*net\.ipv4\.ip_forward.*$|net.ipv4.ip_forward=1|' /etc/sysctl.conf

RUN apt-get update && \
    apt-get install -y libnl-3-200 libnl-route-3-200 libpcap-dev

COPY --from=builder /home/builder/dygre/dygre /usr/bin/dygre

